workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      vars:
        CM_KEYSTORE_PATH: android/app/key.jks
        CM_KEY_ALIAS: upload
    cache:
      cache_paths:
        - ~/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --obfuscate --split-debug-info=build/debug-info
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info
    artifacts:
      - build/app/outputs/apk/**/*.apk
      - build/app/outputs/bundle/**/*.aab
      - build/debug-info/**
    publishing:
      email:
        recipients:
          - senya.kalchoroev@gmail.com
        notify:
          success: true
          failure: true